services:
  bot:
    container_name: unnos-bot
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.bot
    image: unnos-bot
    command: /bin/bash -c "bunx prisma migrate deploy; bun run start:bot"
    environment:
      - DATABASE_URL=${DATABASE_URL}